### ISSUE TITLE
Unable to specify port for ssh_known_hosts

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/users-formula#103]
This just started happening after upgrading to 2015.8:
I have the following clause in my users pillar:

``` yml
    ssh_known_hosts:
      slsapp.com:
        port: 1234
        fingerprint: xx:xx:xx
        enc: ssh-dss
```

This results in:

```
          ID: users_ssh_known_hosts_username_0
    Function: ssh_known_hosts.present
        Name: slsapp.com
      Result: False
     Comment: argument port can not be used in conjunction with argument hash_known_hosts
```

hash_known_hosts is not present, so I'm not sure what is going on here.  I tried to explicitly set hash_known_hosts to False in case it was the default, but it didn't help.
