### ISSUE TITLE
remove_groups causes a failure unless set to True

### ISSUE THREAD

**Issue by edhgoose** [saltstack-formulas/users-formula#147]
Hi, 

I'm seeing a failure regarding the remove_groups setting.

Here's my pillar to start with:

```
users:
  ed:
    fullname: My Full Name
```

And here's what Salt replies:

```
minion:
    Data failed to compile:
----------
    Improperly formatted top file matcher in saltenv OrderedDict([('remove_groups', False)]): False file
```

The minion generates this yaml, taken directly from the debug logs so including the log message before and after:

```
Rendered data from file: /var/cache/salt/minion/files/base/users/init.sls:
# vim: sts=2 ts=2 sw=2 et ai









users_ed_user:

  file.directory:
    - name: /home/ed
    - user: ed
    - group: ed
    - mode: 0750
    - require:
      - user: users_ed_user
      - group: ed
  group.present:
    - name: ed

  user.present:
    - name: ed
    - home: /home/ed
    - shell: /bin/bash
    - gid_from_name: True

    - fullname: My Full Name




    - remove_groups: False
    - groups:
      - ed


    - require:
      - group: ed
























users_/etc/sudoers.d/ed:
  file.absent:
    - name: /etc/sudoers.d/ed


#
# if not salt['cmd.has_exec']('git')
# fails even if git is installed
#
# this doesn't work (Salt bug), therefore need to run state.apply twice
#include:
#  - users
#
#git:
#  pkg.installed:
#    - require_in:
#      - sls: users
#











[DEBUG   ] Results of YAML rendering:
OrderedDict([('users_ed_user', OrderedDict([('file.directory', [OrderedDict([('name', '/home/ed')]), OrderedDict([('user', 'ed')]), OrderedDict([('group', 'ed')]), OrderedDict([('mode', 750)]), OrderedDict([('require', [OrderedDict([('user', 'users_ed_user')]), OrderedDict([('group', 'ed')])])])]), ('group.present', [OrderedDict([('name', 'ed')])]), ('user.present', [OrderedDict([('name', 'ed')]), OrderedDict([('home', '/home/ed')]), OrderedDict([('shell', '/bin/bash')]), OrderedDict([('gid_from_name', True)]), OrderedDict([('fullname', 'My Full Name')]), OrderedDict([('remove_groups', False)]), OrderedDict([('groups', ['ed'])]), OrderedDict([('require', [OrderedDict([('group', 'ed')])])])])])), ('users_/etc/sudoers.d/ed', OrderedDict([('file.absent', [OrderedDict([('name', '/etc/sudoers.d/ed')])])]))])
```

If I comment out the remove_groups line in the User.sls, or set the pillar file to:

```
users:
  ed:
    fullname: My Full Name
    remove_groups: True
```

then the issue goes away and the system works fine.

This is my versions:

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.20.3
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.10-22.54.amzn1.x86_64
         system: Linux
        version: Not Installed
```

And for the minion:

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.9.20-11.31.amzn1.x86_64
         system: Linux
        version: Not Installed
```

Any ideas what's going on?
