### ISSUE TITLE
Add sudo_rules for a user without making them a sudoer

### ISSUE THREAD

**Issue by alexander-bauer** [saltstack-formulas/users-formula#148]
Currently, it does not appear to be possible to add specific sudo rules for a user without making them a full sudoer.

I ran across this use case while configuring my Git server, where I want the `git` user to be able to run a specific `salt-call` command without being able to do anything else. I followed through the logic in `users/init.sls`, and found that the `sudo_rules` and `sudo_defaults` state directives are only formatted if the user is also a sudoer.

For the time being, I am using this approach, but it is somewhat less secure than I would like.

**Comment by aboe76** [comment]
@alexander-bauer you can also declare a file:
```
sudoers:
  included_files:
    /etc/sudoers.d/10-git:
     users:
      git:
        - 'your sudo rule'
```
