### ISSUE TITLE
Users/Groups already exist Errors/state failures

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/users-formula#167]
Is there any pillar to workaround ERRORS/failed states if users already exist?  I want to ensure oracle user, and oracle/dba groups, are present in any database  but [salt only checks locally](https://github.com/saltstack/salt/issues/43208)  

(see also https://github.com/saltstack/salt/issues/45345 and https://github.com/saltstack/salt/issues/45142)

```
  oracle:
    empty_password: True
    home: /home/oracle
    uid: 501
    shell: /bin/bash
    prime_group:
      name: oracle
   {% if not salt['cmd.run']('getent group oracle', output_loglevel='quiet') %}
      gid: 501
   {% endif %}
    optional_groups:
      - dba
      - oracle
```

Thanks
Noel
