### ISSUE TITLE
gitconfig not run though git get installed

### ISSUE THREAD

**Issue by ze42** [saltstack-formulas/users-formula#172]
Having git installed (and modules refreshed) used to work to get gitconfig installed in a single run, but since #169 , the gitconfig is not even tryed anymore.

(dummy example, not tested as it)

```yaml
# git/install_reload
git:
  pkg.installed: []

reload_modules:
  module.run:
  - name: saltutil.refresh_modules
```

```
include:
  - git.install_reload
  - users
```

The sls checks the presence of git *before* doing anything. If pkg is installed by prior states, it would not be checked/updated...

Ideas:
  * Check git presence with `if`/`unless` clause, having it done runtime, but doesn't check if module is reloaded
  * Check at runtime, forcing a refresh_modules if it was not present at sls parsing
  * Simple have a pillar to force bypass the check.

Any suggestions?
