### ISSUE TITLE
createhome doesn't work when the home folder doesn't exist

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/users-formula#181]
For a user 

```
users:
  bob:
    home: /var/home/bob/
    createhome: True
```

The users state fails because useradd can't add a home in `/var/home/bob` since `/var/home` doesn't exist. 

The file.directory depends on the user to exist. We have a sort of chicken and egg problem.
