### ISSUE TITLE
'gid_from_name' is an invalid keyword argument for 'user.present' (=> `usergroup`)

### ISSUE THREAD

**Issue by garethhowell** [saltstack-formulas/users-formula#198]
I've been using this formula for a while. I recently pulled the latest version to overcome an issue where gitconfig failed, and I'm now getting an error.
```
Passed invalid arguments: 'gid_from_name' is an invalid keyword argument for 'user.present'.
```

The state simply calls `users`
The relevant pillar data is
```
users:
  aUser:
    fullname: A User
    createhome: True
    sudouser: True
    sudo_rules:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_auth:
      - <redacted>
    gitconfig:
      user.name: A User
      user.email: <redacted>
```
Running `salt-call state.apply users -l info` results in the contents of this pastebin (last bit only shown)
https://pastebin.com/prne7Xn2
