### ISSUE TITLE
[FEATURE] Implement storing ssh keys for users in separate pillar files

### ISSUE THREAD

**Issue by MurzNN** [saltstack-formulas/users-formula#224]
### Is your feature request related to a problem?
In [pillar.example](https://github.com/saltstack-formulas/users-formula/blob/master/pillar.example) there are example how to read keys from state files:
```yaml
    ssh_keys:
      # or you can provide path to key on Salt fileserver
      privkey: salt://path_to_PRIVATEKEY
      pubkey: salt://path_to_PUBLICKEY
```

But storing private keys in state files is insecure, for example [here](https://serverfault.com/questions/707821/is-there-a-reason-to-store-a-ssh-private-key-in-a-salt-pillar-instead-of-a-file) is recommendation to not do this.

And filling long private key text inside `yaml` is not good solution too, because operating with separate files is much more universal (eg for regenerating, reusing in other scripts).

### Describe the solution you'd like

For solve this problem will be good to implement reading contents if ssh keys from file inside pillar structure. 

[Here](https://github.com/saltstack/salt/issues/18406) is feature request about build-in support for this in SaltStack, so we could use something like this:
```yaml
    ssh_keys:
      # or you can provide path to key on Salt fileserver
      privkey: pillar://path_to_PRIVATEKEY
      pubkey: pillar://path_to_PUBLICKEY
```
but it is closed with recommendation to use [salt.pillar.file_tree](https://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.file_tree.html#module-salt.pillar.file_tree), that isn't suitable for current task.

So, is it possible to implement this feature in users-formula itself? Or maybe you can provide some workaround for this?

### Describe alternatives you've considered

Some alternatives are provided in issues https://github.com/saltstack/salt/issues/3790 and https://github.com/saltstack/salt/issues/1543 but they isn't good.

**Comment by MurzNN** [comment]
Here https://github.com/saltstack-formulas/nginx-formula/blob/master/pillar.example#L291 is example how this is implemented in `nginx-formula`:
```yaml
  certificates:
    'www.example.com':

      # choose one of: deploying this cert by pillar (e.g. in combination with
      # ext_pillar and file_tree)
      # public_cert_pillar: certs:example.com:fullchain.pem
      # private_key_pillar: certs:example.com:privkey.pem
```
