### ISSUE TITLE
Support for Gentoo

### ISSUE THREAD

**Issue by xen0n** [saltstack-formulas/users-formula#37]
Apparently the Gentoo package names are constructed a bit differently from the other platforms... Here's the output from one of the nodes running `state.highstate`:

```
          ID: bash
    Function: pkg.installed
      Result: False
     Comment: Package 'bash' not found (possible matches: app-shells/bash)
     Changes:   
----------
          ID: sudo
    Function: pkg.installed
      Result: False
     Comment: Package 'sudo' not found (possible matches: app-admin/sudo)
     Changes:   
----------
          ID: sudoer-defaults
    Function: file.append
        Name: /etc/sudoers
      Result: False
     Comment: One or more requisite failed
     Changes:   
```

Patch coming soon...
