### ISSUE TITLE
sudo_rules are generated each time

### ISSUE THREAD

**Issue by jryberg** [saltstack-formulas/users-formula#40]
Hi,

Running Ubuntu Server 14.04 on my test server and I noticed that my sudo_rules for my users are generated every time.

```
  test:
    fullname: Test Test
    password: xxxx
    sudouser: True
    sudo_rules:
      - ALL=(ALL:ALL) ALL
    shell: /bin/bash
    ssh_auth:
      - ssh-rsa xxxxx
```

Running salt 2014.1.5

I got the message for every run

```
----------
          ID: validate test sudo rule 0 test ALL=(ALL:ALL) ALL
    Function: cmd.run
        Name: visudo -cf - <<<"$rule"
      Result: True
     Comment: Command "visudo -cf - <<<"$rule"" run
     Changes:   
              ----------
              pid:
                  16196
              retcode:
                  0
              stderr:

              stdout:
                  stdin: parsed OK
----------
```
