### ISSUE TITLE
sudo forcing to use bash

### ISSUE THREAD

**Issue by Koma-Andrea** [saltstack-formulas/users-formula#50]
As bash is not included on all the systems (freebsd for example) i suggest to change this part in init.sls:

```
{% if 'sudo_rules' in user %}
{% for rule in user['sudo_rules'] %}
"validate {{ name }} sudo rule {{ loop.index0 }} {{ name }} {{ rule }}":
  cmd.run:
    - name: 'result=`echo "$rule" | visudo -cf -`; if [ "$result" != "stdin: parsed OK" ]; then echo $result; fi'
    - stateful: True
    - shell: /bin/sh
    - env:
      # Specify the rule via an env var to avoid shell quoting issues.
      - rule: "{{ name }} {{ rule }}"
    - require_in:
      - file: {{ users.sudoers_dir }}{{ name }}
{% endfor %}
```

And to remove the bash as required in sudo.sls

```
# Ensure availability of bash
bash-package:
  pkg.installed:
    - name: {{ users.bash_package }}
```
