### ISSUE TITLE
Rendering fails if 'user_files' used with omitted 'home' attribute

### ISSUE THREAD

**Issue by hatifnatt** [saltstack-formulas/users-formula#99]
#### Pillar
```
users:
  salttestuser:
    fullname: Salt Test User
    password: test123
    user_files:
      enabled: True
      source: salt://users/files/user/salttestuser
```
**Running:**
```root@saltmaster # salt 'somehost' state.apply users test=True```
**Result:**
```
somehost:
    - Rendering SLS 'base:users.user_files' failed: Jinja variable 'dict object' has no attribute 'home'
```
This can be fixed by changing 
```
name: {{ user.home }}
```
to
```
name: {{ salt['pillar.get']( username ~ 'user:home', '/home/' ~ username )}}
```
in 'user_files.sls'. With this change we have default path for home directory if custom path doesn't set in pillar file.
I'm pretty new to Salt so there can be better solution. I will made commit for this.
